.\"
.\" $Id: xfmail.1,v 1.4 1997/04/20 12:03:05 gena Exp $
.\"
.\" Man page for XFMail
.\"
.\"
.TH XFMAIL 1L "Apr 1997" "Version 1.1" "XFMail"
.SH NAME
XFMail \- XForms based mailer application
.\"
.\" setup
.de Cr
.ie n (c)
.el \(co
..
.SH SYNOPSIS
.if n xfmail
.if t  \{
.B xfmail
\}
.SH DESCRIPTION
XFMail is application for sending and receiving E-Mail under X.
It's partially compatible with MH style mailboxes but it does not 
require any mh tools to be installed on the system.

XFMail supports POP and SMTP mail protocols, also it has full
MIME support.

See Help/Contents in the main menu for more info.
.SH SEE ALSO
xforms(5)
.SH AUTHOR
Copyright
.Cr
1995,1996,1997 by Gennady B. Sorokopud
